export const HOME = "/"
export const LOGIN = "/login"
export const REGISTRATION = "/registration"
export const FORGOT_PASSWORD = "/forget"
export const PROFILE = "/profile"
export const SETTINGS = "/settings"
export const POST = "/posts"

export const VERIFY_TOKEN = "/verify/:token"
export const POST_CREATE = POST + "/create"
