export const HOME = "/"
export const LOGIN = "/login"
export const REGISTRATION = "/registration"
export const FORGOT_PASSWORD = "/forget"
export const PROFILE = "/profile"
export const SETTINGS = "/settings"
export const POST = "/posts"

export const VERIFY_TOKEN = "/verify/:token"
export const POST_PAGE = POST + "/:id"
export const POST_CREATE = POST + "/create"
export const POST_UPDATE = POST + "/:id/update"
export const USER_FEED = POST + "/feed"
export const SEARCH_PAGE = POST + "/search"

